### ISSUE TITLE
Connector "blogs" is added to all searches on a multisite if any sub-sites has a non-english site title

### ISSUE THREAD

**Issue by Nikschavan** [xwp/stream#1051]
#### Bug Report

If anyone of the subsites in a network has a non-english site title, Clicking "Search Records" in stream records auto-selects "blogs" as a connector.

Here is a video demonstrating the bug - https://share.getcloudapp.com/d5u0l5YE

#### Expected Behavior
Clicking "Search Records" should not auto-select a connector as that limits the actual search results.

**Here is what I found after some debugging -** 

- Stream, when generating a list of all the sites uses function `sanitize_key()` in [blogs](https://github.com/xwp/stream/blob/31ae9b9362d303a55bd6b5e15cf0ad6a3ec10620/connectors/class-connector-blogs.php#L77) and [mercator](https://github.com/xwp/stream/blob/143d98dae53054b82bbafd406ab2dde3d4952719/connectors/class-connector-mercator.php#L68) connectors, over this non-english text and it is returned as `''`.
- When building the select fields for the connectors, the select field value gets selected from [selected()](https://github.com/xwp/stream/blob/fac60647d704fb7042b2969d3d978c8486219871/classes/class-list-table.php#L750)
- This selected value is then applied to the select field from [admin.js](https://github.com/xwp/stream/blob/fac60647d704fb7042b2969d3d978c8486219871/ui/js/admin.js#L135)

**Comment by oscarssanchez** [comment]
It looks like the foreign sites will not be able to be selected as a result of this bug on my testing. @kasparsd since the value is later escaped: https://github.com/xwp/stream/blob/develop/classes/class-list-table.php#L780 as well as label: https://github.com/xwp/stream/blob/develop/classes/class-list-table.php#L787 and it seems this is not getting saved into the DB, perhaps removing `sanitize_key()` won't do any harm ? 

If so, I'm happy to submit a PR and Unit test!

Thanks!

**Comment by lkraav** [comment]
You could certainly submit the PR so it'd be easy to take a look. Otherwise it'll just get stuck here.

**Comment by oscarssanchez** [comment]
Sounds like a good idea @lkraav  !
