### ISSUE TITLE
Minified files (CSS & JS) are not included in the Composer package

### ISSUE THREAD

**Issue by jazzsequence** [xwp/stream#1255]
# Bug Report
When pulling down the plugin via Composer, the minified CSS/JS files are not included in the package, which results in the admin Stream page(s) being broken if `SCRIPT_DEBUG` is `false`.

The workaround is to hijack the behavior via the `wp_stream_load_min_assets` filter, but obviously the ideal would be to load the minified assets.

```php
add_filter( 'wp_stream_load_min_assets', '__return_false' );
```

It appears that this may be because those files are [explicitly `.gitignore`d](https://github.com/xwp/stream/blob/develop/.gitignore#L16-L19), so a solution may be to just remove those paths from the `.gitignore` file.

## Expected Behavior

Minified CSS and JS files are included in the Composer release packages.

## Actual Behavior

Only the compiled, unminified CSS and JS files are included, resulting in 404s for all the minified versions.

## Steps to Reproduce the Problem
1. Composer require `xwp/stream` as a dependency
2. Load/include the plugin
3. Navigate to the Stream admin page

## Screenshots

![Screen Shot 2021-04-28 at 12 46 54 PM](https://user-images.githubusercontent.com/991511/116456917-09193980-a820-11eb-983f-762600ac9769.png)

## System Information

- Stream plugin version: 3.6.2
- WordPress version: 5.7.1
- PHP version: 7.4
- Browser: Firefox
- Computer operating system: MacOS

**Comment by kasparsd** [comment]
Thanks for the report @jazzsequence!

Would it be possible for you to use the [wpackagist.org repository](https://wpackagist.org/) which mirrors the plugin source from WP.org?

Alternatively, we've created the [stream-dist](https://github.com/xwp/stream-dist) repository which contains the full plugin bundles with all artifacts when [a new release is tagged](https://github.com/xwp/stream/blob/c65e738dab15e1d477fd8d8d8f7a8f9671e0734f/.travis.yml#L49-L61). However, we never set the Packagist.org repo to use it because we didn't get to test it thoroughly. I've switched it now, though. Could you please try it now?

**Comment by jazzsequence** [comment]
The way our architecture is set up, we can't actually use wpackagist. However, I can test the Packagist.org package again and report back. Thanks!

**Comment by jazzsequence** [comment]
Yup, that works! Thanks again, that was easy 😁
