### ISSUE TITLE
BuddyPress connector can fatal in network admin

### ISSUE THREAD

**Issue by dd32** [xwp/stream#1516]
# Bug Report

```
Uncaught Error: Call to undefined function groups_get_group()
wp-content/plugins/stream/connectors/class-connector-buddypress.php:210
```

It appears that BuddyPress group functions are not available within network admin, likely because the Groups component isn't activated in the context of the site.
As a result, this may also be able to be triggered by enabling groups, performing actions, and then disabling groups. I haven't tested this.

## Expected Behavior

I'd expect it to gracefully degrade when BuddyPress groups functions aren't available.

## Actual Behavior

A fatal error is encountered.

## Steps to Reproduce the Problem

1. Have a Multisite network. Have BuddyPress & Stream Network Activated
2. Join a group
3. View the Stream network admin list
4. Receive fatal.

## System Information

- Stream plugin version: 4.0.0
- BuddyPress plugin version: 14.x
- WordPress version: Trunk
- PHP version: 7.4

**Comment by tharsheblows** [comment]
To reproduce on the current local environment:

 1. Have a Multisite network. Have BuddyPress & Stream Network Activated
 2. add filter `add_filter( 'wp_stream_is_network_activated', '__return_true' );` to show Stream in the admin (there is a mismatch in the check in the local environment, we need to fix that)
 3. On the individual site in BuddyPress settings, enable Groups
 4. On the Network BuddyPress settings, make sure Groups are not enabled
 5. Join a group
 6. Fatal error in Network Stream log

This also causes a fatal error when groups were enabled but then disabled.

As a workaround, you can enable Groups in the Network's BuddyPress settings but we will still fix this because it shouldn't happen.
