### ISSUE TITLE
Updated Unit Tests

### ISSUE THREAD

**Issue by lukecarbis** [xwp/stream#611]
Our unit tests are written primarily for the currently released version of Stream. They should be updated for Stream 2.0 to include things like the extensions and API.

**Comment by fjarrett** [comment]
@solace Would you be up for helping with this in some way?

**Comment by solace** [comment]
@fjarrett Can do, what's the timeframe for this?

**Comment by fjarrett** [comment]
@solace Medium priority, API things would come first.

**Comment by solace** [comment]
@fjarrett Let me know when the use cases that need testing have been compiled.

**Comment by fjarrett** [comment]
@solace We basically need to cover as many [Core Connector](https://github.com/wp-stream/stream/wiki/Connectors-Reference#core-connectors) actions as possible and validate each Stream record that is created. They are all documented there in the project wiki.

Some of the actions have multiple contexts within their connector that will apply. It will be easier for me to explain that over a call.

**Comment by solace** [comment]
@fjarrett I'll a little time to go over that, will have a dig through to get familiar with the code and docs first, then we can arrange a chat next week to go over any hazy bits.

**Comment by solace** [comment]
@fjarrett 

1. Having a poke around, I see the `tests` directory in the Stream plugin.  Are there directions on how to run the tests just for the plugin? I'm trying various permutations around `phpunit` but may be missing something blatantly obvious.

2. Do the tests that currently exists, even though they are for the previous version, cover any of the cases in the wiki? Or should I be aiming to blow away what's there right now and do it from scratch?

**Comment by solace** [comment]
@fjarrett 

Okay figured it out (I think). In vvv, in the `plugins/stream/` directory, run `phpunit` and it will run all the tests in the `plugins/stream/tests/` directory with 'no news is good news' type of results. Doesn't list the tests executed, just the number run and passed. Only dumps extra info if there are failures.

The current suite of tests pass.

It doesn't appear as though any of the Connector contexts are covered at this stage, just general set up and instantiation type tests.

Read to have a chat about any special cases in the Connector Reference when you are.

**Comment by solace** [comment]
@fjarrett :

* Posts: Done
* User: Done except *Session* context. Login and Logout send headers, and Lost Password's action function is not globally accessible or file-loadable. These will probably require the UAT tests we discussed.
* Widgets: Done except Created and Deleted. Do you have suggestions on how to programmatically create the widgets so that it will trigger those two actions?
* Settings: The `$whitelist_options` list used for setting contexts isn't available in the unit tests, possibly because it's only accessible when accessed via the UI.  This results in those settings having all the same context in testing. Also need suggestions for testing the Network context params. Would we need to run the unit tests in both standalone and multisite installs to ensure coverage? Also not able to update the `wp_stream` and `custom background/header` settings programmatically. Will require suggestions on this as well.
* Comments: Done except Throttled, once we've sorted out updating the `wp_stream` settings as described above, should be able to test this.
* Editor: Not sure how to do this programmatically, is it something that can be done, or will it require UAT tests instead?
* Installer: Missed this one, but can Installed be done programmatically?
* Media: Done. Except, what sort of attachments are classified as Interactive and Code? 
* Menus: Done, except Assigned and Unassigned. Unit test environment doesn't seem to let me set `theme_mods`. It's retrieved as null and does nothing when set. Not sure why. Thoughts?
* Taxonomies: Done.

**Comment by fjarrett** [comment]
@solace Awesome sauce.

Yes, like you said, for everything we weren't able to get sufficient UT coverage on, we can with UAT.

Regarding the Code and Interactive media, I have no idea. Core supports them but I haven't the slightest clue what they mean. Haha :smile:

**Comment by fjarrett** [comment]
@solace Is there a PR coming for this? Please issue against `develop`.

**Comment by solace** [comment]
@fjarrett If there's anything in my questions that you think can be done programmatically, I'll add those before I put in a PR. Otherwise if you think that's about it, I'll create the PR.

I take it we'll create tests for the plugins later on after the next feature push?

**Comment by fjarrett** [comment]
@solace Yes, this is good for now, and yes, plugin connectors can come later as well.
