### ISSUE TITLE
Datepicker display issues when there's no outgoing connection

### ISSUE THREAD

**Issue by lukecarbis** [xwp/stream#742]
When there's no internet connection (say, on a local dev environment), some there are some display issues around the datepicker in the filters area of the Stream screen.

**Comment by lukecarbis** [comment]
Reported here: https://wordpress.org/support/topic/some-bugs-13?replies=3

Stream doesn't use a datepicker. Putting this down to another plugin's fault.

**Comment by cameronjonesweb** [comment]
I don't mean to be rude, but you're wrong. I disabled all plugins except Stream and the datepicker still shows when there is no connection. It is also completely illogical that it would be another plugin considering it only appears on the Stream feed. 
If it doesn't use a datepicker, it seems to reference it an awful lot: https://github.com/xwp/stream/search?utf8=%E2%9C%93&q=datepicker&type=Code
I even pointed out the exact issue in the WordPress support thread, the issue is you are trying to enqueue jQuery UI from Google's CDN and when there is no connection it can't be accessed. And it's found on line 505 of `classes/class-admin.php`. Save the jQuery UI CSS file in your plugin css directory and replace line 505 of `classes/class-admin.php` with:
`if( file_exists( '//ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/themes/base/jquery-ui.css' ) ) {
	wp_register_style( 'jquery-ui', '//ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/themes/base/jquery-ui.css', array(), '1.10.1' );
} else {
	wp_register_style( 'jquery-ui', $this->plugin->locations['url'] . 'ui/css/jquery-ui.css', array(), '1.10.1' );
}`

**Comment by lukecarbis** [comment]
My bad. We do use it, but it's kinda hidden (have to choose a date range of custom). Sorry @cameronjonesweb. Thanks for your persistence.

Working on a fix now.
