### ISSUE TITLE
Stream's "Voice"

### ISSUE THREAD

**Issue by lukecarbis** [xwp/stream#760]
Stream has various dialogs and messaging, including a Summary for every action that it logs.

I'd like to explore the idea of establishing a voice for this messaging. What sort of personality should Stream have?

How can we establish consistency with our language?

**Comment by Japh** [comment]
Oh, I love this idea!

**Comment by jordesign** [comment]
+1 for this - definitely helps to have a certain 'personality' through the messaging

**Comment by jwold** [comment]
The first thing that comes to mind for me is the voice and messaging with Mailchimp. It of course has a more playful tone, going along with their logo/mascott. The personality is kind of fun and makes it very memorable. 

Along those veins having some kind of a tone can help a lot with consistency across the plugin. 

Another more extreme (and hilarious) example is: http://www.meetcarrot.com/

**Comment by lukecarbis** [comment]
@jwold Love both Carrot and Mailchimp, but I'm not sure if they're the right approach for Stream. I'm not really sure how to go about "deciding" what a voice sounds like, though. Could you suggest next steps?

**Comment by jwold** [comment]
@lukecarbis I agree that those two voices would be too playful for Stream. My familiarity and use of Stream is a bit limited. I've only been using it for the past month or two on my development and personal websites. However, in the time I've used it the reason I've installed them is for security, so that I can trace back my steps in case something goes wrong. It's security for me. I imagine that I'll find more uses for it as I go forward. 

As far as a voice is concerned though, I haven't really sensed anything specific that would be good for Stream. When I think about it I imagine wording that is re-assuring and has an attitude of being there for me and covering me just in case. 

For instance, when I look at Backupbuddy, their copy re-assures me that they'll add security (and it will be easy) for my business. 

"SAVING WORDPRESS SITES AROUND THE WORLD SINCE 2010"
"SET UP BACKUPBUDDY ON YOUR SITE IN JUST 1 MINUTE FLAT"
"SAVE HOURS OF WORK (AND WE MEAN HOURS)"
"STORE YOUR BACKUPS SAFELY OFFSITE"
"ALSO PRONOUNCED "SAVING YOUR BACON""

I really like the use of "your" and "we", it makes it feel personal.

Now, for Stream I'm not saying this works, but it's another observation I've had. Not sure if this is useful!

For next steps though I'd recommend, at a basic level, some agreement on what the goal of the voice is. Right now I'd throw out "security" and "ease".

If we can settle on a few words that describe what Stream does, then it might help inform the voice.

**Comment by kopepasah** [comment]
@kasparsd @derekherman while I do like the idea of this issue, I feel it may not be the right focus for Stream. I feel setting a "voice" for the plugin would be a fun idea, it could make translations more complicated and overall may set the tone of the plugin to be too "look at me". 

IMO, Stream should be as silent as possible and only display relevant information when a user needs it. Thoughts?

**Comment by kasparsd** [comment]
@kopepasah I share you view on this. Stream is a utility plugin with a professional and serious purpose. I feel like neutral and professional voice serves this purpose well.

I think we can probably close this as there are no clear action steps for how to "solve" this, at least right now.

**Comment by jwold** [comment]
I'm good with closing this. Thanks!
