### ISSUE TITLE
Conflict with WP Slimstat premium add-ons

### ISSUE THREAD

**Issue by mundschenk-at** [xwp/stream#820]
Having add-ons for the site analytics plugin "WP Slimstat" installed makes Stream unusable because every few hours there is an entry generated for each add-on. Since there is no pattern matching for the summary text, there is no possibility to filter these entries. They look like this:  `"external_updates-wp-slimstat-heatmap" setting was updated`.

**Comment by lukecarbis** [comment]
Fixing this would require a WP Slimstat connector, to hijack the setting and record it differently under a WP Slimstat context instead of a Settings context (or ignore it).

The alternative would be matching the summary text, which I don't think is a good idea as it introduces added complexity to the already quite complex Exclude settings screen.

Any other opinions? cc. @chacha

**Comment by chacha** [comment]
I don't think this is something that we can do in the Stream core. You could always filter out by multiple things (including a summary) by using the `wp_stream_log_data` on an individual site. But, I think that would be stepping outside of our scope and might create some confusion.

**Comment by mundschenk-at** [comment]
@chacha If that's a filter name, it would be great if you could point me to the appropriate documentation.

**Comment by chacha** [comment]
@mundschenk-at I find documentation in e morning, but at the moment I point you towards the source code for the base connector class. https://github.com/xwp/stream/blob/develop/classes/class-connector.php#L99
