### ISSUE TITLE
Timestamp inconsistencies

### ISSUE THREAD

**Issue by lukecarbis** [xwp/stream#837]
I have Easy Digital Downloads and its extension EDD Points and Rewards installed and activated.

I set up EDD and its extension so that each user get rewarded for 500 points after registration.

The issue is, when a user is registered, in Stream I can see the entry of registration logged as "one minute ago", along with a second entry of points reward logged as "8 hours ago".

This is obviously a bug that one of them is not aware of time zone settings or so.

Meanwhile, I notice that all email event is logged with wrong time stamp too. I use Postman SMTP for the emails.

Please can we confirm this, and if it is Stream's issue, can we please have a fix for that?

**Comment by chacha** [comment]
After talking with @lukecarbis, it looks like we're going to need to do an analysis on the full set of how we get our times, as it appears that there are different areas where times are not being set correctly.

I've experienced problems where my time logs are actually just a couple minutes off (5-7), whereas the original issue is dealing with time discrepancies in much larger numbers.

**Comment by daveglines** [comment]
Howdy, y'all. First off -- great plugin. Stream will be a standard plugin for a product we are building. I am finding one issue though that's leading to a bug fix/feature request, and I believe it is along the same lines as what is posted here. 

The feature request is that Stream leverage the time zone as set at WP Admin > Settings > General > Timezone. What I am understanding from my development team is that the time is being set in a few different places. Here in Chicago for example, we see Stream activity dates logged as 9 hours ahead of the timezone set in WP, which is US Pacific Time.

Because of this discrepancy, it is more difficult to make this data user-facing in some instances, when we would indeed really like to do that. 

Any assistance is greatly appreciated.

**Comment by daveglines** [comment]
Upon further research, it turns out this was from our end via another plugin. This is no longer an issue for us.
