### ISSUE TITLE
Unidentified user

### ISSUE THREAD

**Issue by tillkruss** [xwp/stream#922]
I'm seeing a lot of updated from unidentified users. The user id is `0`. What or who is that?

In case these are internal calls, it should say "WordPress" and use the real WP logo instead of the custom black lowercase one.

<img width="1132" alt="screen shot 2017-04-22 at 11 57 51 am" src="https://cloud.githubusercontent.com/assets/665029/25307283/0418f0ee-2753-11e7-9b44-025116d56527.png">

**Comment by majeem** [comment]
Are you using a plugin for example like a membership plugin or similar which can update user status? Also can you identify the IP? Is that one of yours or your colleague's ? Probably that will shed some light.

**Comment by tillkruss** [comment]
Yes, we're using AccessAlly (Ontraport membership plugin) on that installation. I can't identify the IP address, but I'm pretty sure it's AccessAlly.

**Comment by majeem** [comment]
From what I have seen, most membership plugins uses the WP Members profiles as the base. So when we change a setting (for example the access levels for a specific user group) the membership plugin updates the User profile for all included users at once. 

As far as Stream is concerned this is done by the Plugin not specifically by an user. I have had the same experience with "WP Member" plugin. 

I think if there was a connector for AccessAlly, stream would have been able to identify this change from an user level. I am not sure.

**Comment by majeem** [comment]
I am curious whether Stream logged an activity from AccessAlly just before these whole bunch of User Profile updates. Did it?

**Comment by tillkruss** [comment]
Ah, okay. No AccessAlly records ever, only "N/A".

**Comment by kopepasah** [comment]
@tillkruss without access to the AccessAlly plugin or service, it is difficult to troubleshoot this issue. However, the log is likely due to an update from some background service within AccessAlly. You can see within the logs that each profile update is within seconds of each other (which screams 🤖), and while this is not a problem in itself, it does mean the logs will be bloated with every profile update through the plugin. 

There is potentially a way for AccessAlly to integrate with Stream, but I am not certain they are interested building that functionality. A more immediate solution could be to limit the logs of profile updates to just a specific set of data that is loggable in Stream.

**Comment by tillkruss** [comment]
We moved away to Jetpacks activity logs.
